### ISSUE TITLE
Design a software platform and put needed entities together

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#15]
Create a software platform diagram and put together entities of the project.

**Comment by miladjafary** [comment]
I am going to work on this.

**Comment by VahidGh** [comment]
@miladjafary, great! welcome to the ChannelWorm.

**Comment by miladjafary** [comment]
@VahidGh please list exist related LIB for this project(Such as plot.ly and some thing like this) which we should connect them to gather for building back end.

**Comment by VahidGh** [comment]
@miladjafary, You can find different modules and resources possibly could be used, in related issues. I've categorized them under [these milestones](https://github.com/VahidGh/ChannelWorm/milestones).
Also, I've defined our objectives (which could be considered as our modules) and use cases (see [this doc](http://channelworm.readthedocs.org)).
If you could propose your design pattern for such a software, then we can work more on the architecture and put modules and libs together.

**Comment by miladjafary** [comment]
@VahidGh As I remember , you list some related tools such as plot.ly 
For accelerating do this task I want to know related exist API for our propose. So help me more in this subject if it possible
Thank You!

**Comment by VahidGh** [comment]
@miladjafary, regarding the digitization and plotting process, you can find needed info in #17.
I think this issue could be a good one as a starting point for programming with Python.

**Comment by miladjafary** [comment]
@VahidGh  Great! 
It's good for me also it could be help me in system design.

**Comment by miladjafary** [comment]
@VahidGh  @travs 
I research in different  architecture and design pattern and I think that the suitable architecture for back end of our project is Micro service. Because we have different API and module which could be in different language. For example in #17 the digitization process of patch-clamp studies could be implemented via the WebPlotDigitizer and drawing chart of result could be implemented by http://highcharts.com or any thing else.

Another example could be PyOpenWorm and MySQL.

You can find more about Micro services in http://martinfowler.com/articles/microservices.html which is great article written by Martin Fowler 

@VahidGh @travs what's your idea?

**Comment by joebowen** [comment]
We started a Django project at OpenShift.com here;
http://channelwormdjango-channelworm.rhcloud.com/  I can get you the needed
access information if you want to work with it or we can try something
different.

**Comment by miladjafary** [comment]
@joebowen  Please send me the access information if it possible

**Comment by joebowen** [comment]
@miladjafary I just need your ssh public key (https://developers.openshift.com/en/managing-remote-connection.html) and if you create an OpenShift account and give me the account username, I can give you access there as well.  Just send those to me though another channel and I create the permissions for you.

**Comment by slarson** [comment]
@miladjafary @VahidGh @travs @joebowen I think with your last release, this is closed :)
