### ISSUE TITLE
Cell data model

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#18]
Quoting @VahidGh 
>Every cell has 0-n ion channel with these properties:
>* membrane capacitance
>* cell surface area
>* internal ion concentration

We have had some discussion about this in #7, but it would be good to define this problem more clearly here.

There exists a [Cell data model in PyOpenWorm already](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#cell-name-string), though it does not include any of the parameters Vahid listed above.

To summarize the discussion as I understand it:
1. Since they are important to modelling and simulating ion channels, we need these cell parameters stored somewhere.
2. Since the parameters are *cell* parameters, they should be stored along with the cell data model.
3. Since the parameters are dynamic, we will just store the *initial* states in the database.

Now, as Vahid mentions, these properties differ from cell to cell, so the data model should accommodate for this. 
PyOpenWorm (at least on the main branch) attempts to reconstruct the organism's anatomical data one-to-one (i.e. every cell in the organism (ex: ADAL or P11) has an entry as a Cell in the db). 
My question is whether the cellular data useful for ion channel modelling (ex: surface area) is specific enough to include in this type of cataloging db. Surely cell surface area differs for ADAL (or any particular cell) between organisms.

If this is the case, then our cell models will differ from those in the main PyOpenWorm branch, but this is not a problem, just something I will have to keep in mind.

If this is not clear don't hesitate to ask what the heck I'm talking about :stuck_out_tongue:

**Comment by VahidGh** [comment]
I think what we need would be part of the [cell morphology data model](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#morphology-neuroml-morphology). If it is possible to include such data under this data model, that would be great (although internal ion concentration could be in other data model, such as cell's metabolites).
I don't know if we have morphological data for each cell right now, and also if it is possible to store more than one value for these parameters in the PyOW (because different resources may assert different values). 
If we don't have such a data model, we can start to implement it for this issue.
I think it would be better to integrate data models as much as possible.

**Comment by VahidGh** [comment]
[This study](http://www.sciencedirect.com/science/article/pii/S0092867412007763) could be a good reference for such a model.

**Comment by travs** [comment]
Implementation issue in openworm/PyOpenWorm#133
