### ISSUE TITLE
Integrate SciUnit and Nosetest frameworks

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#36]
### Currently 
The [current test example](https://github.com/VahidGh/ChannelWorm/blob/tests/tests/hello_model_test.py#L82) uses an `assert` statement (Python standard library) in order to run on Travis CI with NoseTest. 

This can [be improved](https://github.com/VahidGh/ChannelWorm/commit/5b5178641d52ace4a37c9aa3144ceb98edb72c94#commitcomment-11295991), but ultimately the `assert` is wrapped around a SciUnit boolean Score, so if the score is `True`, the NoseTest passes.

### What we want
This is fine for boolean scores, but more complex Score types (e.g. scores generated from any statistical measure) will have more complex values. Ultimately the result must be expressed as a boolean (pass/fail), which will likely be whether or not a score falls within a certain acceptable range.

@rgerkin 
How can we organize our code such that these "acceptable range" calculations are exposed to Travis CI and automated testing (i.e. using NoseTest to check the `assert` results).

Do you think the SciUnit Tests should have the `assert` statements inside them, or should these statements be inside the Scores themselves? Or perhaps we could have a file of SciUnit tests/suites, and perform the acceptable range calculations on them from another file of standard python unit tests.

Thoughts?

@gsarma

**Comment by travs** [comment]
Update:

This is the integration I had in mind. Let me know what you think and we can edit the drawing.

![](https://docs.google.com/drawings/d/1ieXXSqeWZd23RBX76yU0sDwEW03s4yeslC7XOYLXKpQ/pub?w=1394&h=687)

**Comment by rgerkin** [comment]
In the longer run I think all the SciUnit tests you want to run should be expressed in an IPython/Jupyter notebook that loads, instantiates, and executes all tests.  One Nose unit test can be to run this notebook.  The only error that you would want to raise would be if the notebook does not successfully execute (i.e. the test produces an error).  This can be a totally uncaught error, or a returned sciunit.ErrorScore, which is basically a N/A with an error message.  sciunit.ErrorScore can be used with caught errors so the rest of the tests can still run.  

So overall I think TravisCI shouldn't be raising errors because a sciunit Score changes in some simple way, like maybe we thought that a numerical score of < 40 should be a pass, and now we get 41.  Is that really worth raising an error via assert for?  I feel like that's something that should be independently investigated, by considering all the other scores along with it, and looking at the notebook output.  Or maybe some scores are so horrible that you should raise an error, because it indicates the simulation is just way, way off.

**Comment by travs** [comment]
@rgerkin 
I still think that TravisCI should run some tests on the models but, as you say, perhaps this is better left to basic sanity checks than to model evaluation per se. This sanity checking would still require `assert` statements to be seen by Nose, though. 
Perhaps even producing an output/score could constitute as "sane" for TravisCI's purposes.

I have created #48 to reflect the distinction between these types of tests and range validation.

**Comment by travs** [comment]
[Here](https://github.com/VahidGh/ChannelWorm/blob/06d164849e43d931c7582dbd6909b68357545d4f/tests/hello_model_test.py) is a prototypical implementation of integrating the sciunit and nosetest frameworks. We can iterate on this as we go.

Also see #48
