### ISSUE TITLE
Where should we implement SciUnit Capabilities?

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#42]
After discussions with @gsarma, it became apparent that there are currently two "representations" of the model, one to do with the database (PyOpenWorm), the other written NeuroML2. 

When implementing a Capability like [`Generates_IV_Curve`](https://github.com/VahidGh/ChannelWorm/issues/41), where should the implemented methods go? 

It would not be appropriate to implement the python methods in the NeuroML2 file, but the database does not seem like the correct place either. Should there be a third representation of the model (a `.py` file/class) that holds the implemented methods?

What do you guys think?
@slarson @VahidGh @rgerkin

**Comment by VahidGh** [comment]
@travs, My suggestion is, we can have a method to generate IV curves from NeuroML files within pyNeuroML (which is now implemented by @Rayner's code), then a generic capability from SciUnit which does a unit test on IV curves, uses this method. And finally our validation class in CW calls this capability for validation purposes (I've also considered a class for validation in my pipeline structure).
And regarding duplication issue in storage and representation of models, there is a [plan](http://pyopenworm.readthedocs.org/en/alpha0.5/api.html#neuroml) to build an API to generate NeuroML files using PyOW. if it is possible to implement this API, then we can store parameters within a DB and then generate NeuroML files, when needed (in different sub-projects of the OW), but for now we can use just NeuroML files.

**Comment by slarson** [comment]
There's two issues -- where is the "right" place to implement this, and
where is the "expedient" place to implement this.  I think the pyNeuroML
suggestion is reasonable for the "right" place, but there's a fair bit of
experimentation we may need to do to get the methods right, and it is
possible that the overhead of working with pyNeuroML makes it harder to do
this.

I'd suggest to start with the "expedient" place, which would be inside the
test functions themselves first, make sure it works, and then have an issue
for porting the methods back out to pyNeuroML, PyOpenWorm, or whatever
library makes sense, once we can evaluate what that right place may be.
Point is, most important is to close the loop on tests that work and do
sensible things, and not get too bogged down / roadblocked on the way there.
ᐧ

**Comment by gsarma** [comment]
There is also an intermediate solution, which is to simply store the names of the capabilities in the NML2 representation, but not the full Python code itself.  This gives us some degree of redundancy, and makes the writers of NML files aware of the fact that there are model validation steps further down the pipeline.  I tend to agree with @slarson on simply pursuing the expedient strategy for now.

**Comment by VahidGh** [comment]
@slarson, agreed.

**Comment by rgerkin** [comment]
Following the [NeuronUnit](http://github.com/scidash/neuronunit) model, I'd implement them there, or even in someother XUnit, e.g. WormUnit, ChannelUnit, or whatever you might want to call it.  If I do this, I'm likely to use PyNeuroML as part of the implementation since I have independent reasons for wanting to push development forward on that end.  Any call to e.g. receive_current() is implicitly a call to run the simulation or get a cached version of the simulation, which means it will call a run_nml() or something that will probably just be calling PyNeuroML things.  

@gsarma I'd like to eventually be able to store the capability names in NML, but the capabilities may evolve quickly for a while, so it may be better to wait until they are more mature before going that route.  Ideally, I'd like to have a whole modeling ontology be driving the names and hierarchy of capabilities, e.g. Computational Neuroscience Ontology, but that's a pretty lofty goal.

**Comment by rgerkin** [comment]
Is it correct that no one has worked on the implementation yet?  I can probably get started on that.

**Comment by slarson** [comment]
That's right, there's just the [stub implementation here](https://github.com/VahidGh/ChannelWorm/blob/8fc855a6dd6f919a1d004e722c42f0b5199668f3/tests/capabilities.py)

**Comment by travs** [comment]
@rgerkin made an issue for it (#47)

Since we have decided where to implement them for now, I think it is safe to close this issue and track development in #47
