### ISSUE TITLE
Implement existing SciUnit Capabilities

### ISSUE THREAD

**Issue by travs** [VahidGh/ChannelWorm#47]
[Over here](https://github.com/VahidGh/ChannelWorm/blob/8fc855a6dd6f919a1d004e722c42f0b5199668f3/tests/capabilities.py) we have some Capabilities enumerated as stubs, but not yet implemented.

@rgerkin

**Comment by rgerkin** [comment]
I'm starting this today.

**Comment by travs** [comment]
@rgerkin 
Excellent, thanks!

I've merged everything to do with testing into the master branch today, in case you're wondering where to branch from.

We also have a sample generated IV curve [over here](https://github.com/VahidGh/ChannelWorm/tree/master/scripts). It's not correct, but may be useful for knowing what output may look like.

**Comment by rgerkin** [comment]
@travs I missed this until just now.  The [script you referenced](https://github.com/VahidGh/ChannelWorm/tree/master/scripts) is now obsolete after my changes [here](https://github.com/NeuroML/pyNeuroML/pull/6) and demonstrated [here](https://github.com/VahidGh/ChannelWorm/blob/tests/tests/IVCurve_Model.ipynb), which allow you to run NML2ChannelAnalysis through a new run function, instead of doing subprocess magic.  

I ended up creating a new tests branch (it existed earlier in the day but I guess you merged it into master in the interim) so feel free to merge that back into master as well.  I think I only changed the notebook and made a .gitignore update.  

Lastly, that script you referenced has a K+ channel IV curve, but the Figure 2B IV Curve from doi:10.1083/jcb.200203055, which I constructed in my notebook using the ChannelWorm.cwFitter.Initiator, is for a Ca2+ channel.  So I compared it to the Cav1 model in my notebook -- correct me if I'm wrong.

**Comment by rgerkin** [comment]
@travs Biggest outstanding issue for me to get this into SciUnit format is that NML2ChannelAnalysis.run() (main() in the master branch) does too much stuff in one function.  I'd like to make it a lot more modular, so I can separate the construction and analysis of the IV curve from the generation and running of simulations.  I discuss this [here](https://github.com/NeuroML/pyNeuroML/issues/7)

**Comment by rgerkin** [comment]
@travs Everything is working in SciUnit [here](https://github.com/VahidGh/ChannelWorm/blob/tests/tests/IVCurve_Model.ipynb), except as noted in #96.  All model and test interface in SciUnit is shown there.

**Comment by travs** [comment]
@rgerkin 
Excellent! Thanks for this Rick. 
Will add a comment to the pull request to automatically close this when it is merged.
