### ISSUE TITLE
Syncing the db and models between the repo and server

### ISSUE THREAD

**Issue by VahidGh** [VahidGh/ChannelWorm#90]
As with [this commit](https://github.com/VahidGh/ChannelWorm/commit/978b25d0c655be06b688117d9a5e38110d4c1a84), the local DB will be excluded from getting synced with the server.
We need to do something like `python manage.py migrate` to apply new changes on the tables but not affecting data.
Also it would be nice if we could consider a separate branch to occasionally sync back the DB from the server to the repo.

**Comment by VahidGh** [comment]
@joebowen, what do you think? following previous discussions.

**Comment by joebowen** [comment]
@VahidGh

We could add a `python manage.py migrate` to the cron script to handle applying the new changes.  Do you think we'll have an issue if that's occurring every minute with the cron task?  We could always reduce this to an hourly job, but it's probably best if it happens with the main cron update so that the website doesn't get updated and then take an hour to migrate the db.

As far as syncing the db back to the repo.  

We discussed a cron job (but not a minutely cron job), which could work although I have a few concerns about what might happen if someone committed something in the middle of that process.  I think if we reduced the process to a daily or weekly process, then whoever is making changes will just have to know that they shouldn't commit within the window.  

The other idea we discussed was a manual process, which could work just as well but would have to be maintained.  For this, I think we should still generate a script that does the heavy lifting but have the script kicked off in a manual fashion.  One draw back to this, the desktop that the script is running on will have to be given permissions to the openshift repo.  It's not hard to do, but it will mean that not just anyone can run the sync script without first adding the desktop's public ssh key to the openshift account.

I think, either way, we should create a script to handle the db sync and we can probably decide down the road how to deploy it.  My impression of the script will be something that syncs both repos, copies the db from the openshift to github folder, then adds and commits the change to the github repo.

**Comment by VahidGh** [comment]
@joebowen, As for the first issue, if `python manage.py migrate` is OK, unless doesn't affect data itself. And I don't think there would be any problem with occurring every minute. We can test it... 

And for the second one, I was thinking about having a different branch (not master) which gets the latest update from the serve, using a daily cronjob. Then we can manually merge this one with the master branch, whenever we want :)

**Comment by joebowen** [comment]
@VahidGh as far as the migrate, I'm not familiar enough with django to know if it affects the data, but we can look into it.

For the second one, I like that idea.  That should be pretty easy to setup and shouldn't be too risky.

**Comment by VahidGh** [comment]
The migration issue resolved via 64ac54b8f4cba2c6bcb6407d2e7baeb2d6ae0f68.

**Comment by travs** [comment]
@VahidGh Is this issue finished?

**Comment by VahidGh** [comment]
Yes, for the first one. And for the second issue, I'm getting a backup from DB by demand.
